<a href="https://colab.research.google.com/github/neeraj-pola/Churn/blob/main/churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv("churn.csv")
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(x[:, 16])

[['Female' 0 'Yes' ... 'Electronic check' 29.85 '29.85']
 ['Male' 0 'No' ... 'Mailed check' 56.95 '1889.5']
 ['Male' 0 'No' ... 'Mailed check' 53.85 '108.15']
 ...
 ['Female' 0 'Yes' ... 'Electronic check' 29.6 '346.45']
 ['Male' 1 'Yes' ... 'Mailed check' 74.4 '306.6']
 ['Male' 0 'No' ... 'Bank transfer (automatic)' 105.65 '6844.5']]
['Electronic check' 'Mailed check' 'Mailed check' ... 'Electronic check'
 'Mailed check' 'Bank transfer (automatic)']


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
x[:, 0] = le.fit_transform(x[:, 0])
x[:, 2] = le.fit_transform(x[:, 2])
x[:, 3] = le.fit_transform(x[:, 3])

#5-16 columns can also be done by one hot encoding

x[:, 5] = le.fit_transform(x[:, 5])
x[:, 6] = le.fit_transform(x[:, 6])
x[:, 7] = le.fit_transform(x[:, 7])
x[:, 8] = le.fit_transform(x[:, 8])
x[:, 9] = le.fit_transform(x[:, 9])
x[:, 10] = le.fit_transform(x[:, 10])
x[:, 11] = le.fit_transform(x[:, 11])
x[:, 12] = le.fit_transform(x[:, 12])
x[:, 13] = le.fit_transform(x[:, 13])
x[:, 14] = le.fit_transform(x[:, 14])
x[:, 15] = le.fit_transform(x[:, 15])
x[:, 16] = le.fit_transform(x[:, 16])
x[:, -1] = le.fit_transform(x[:, -1])
print(x)

[[0 0 1 ... 2 29.85 2505]
 [1 0 0 ... 3 56.95 1466]
 [1 0 0 ... 3 53.85 157]
 ...
 [0 0 1 ... 2 29.6 2994]
 [1 1 1 ... 3 74.4 2660]
 [1 0 0 ... 0 105.65 5407]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=5)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=5)
classifier.fit(x_train,y_train)


LogisticRegression(random_state=5)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.7960246095598675